# Site settings
title: hkminegod
email: i@choyin.me
description: Hi. I am hkminegod @ Github

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/choyiny
  - title: youtube
    url: http://youtube.com/techmastary
  - title: github
    url: http://github.com/hkminegod

# Postal address (add as many lines as necessary)
address:
  - line: 127.0.0.1
  - line: Localhost

# Build settings
markdown: kramdown
permalink: pretty
